<a href="https://colab.research.google.com/github/uteyechea/Introducuccion-a-matrices-en-python/blob/main/Introduccion_a_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matematicas Discretas: Introduccion a matrices

In [ ]:
#Import all necessary dependencies
import numpy as np

##Ejemplos de matrices

In [ ]:
A=np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9]
])

B = np.array([
              [-1,1,1],
              [0,1,0],
              [1,-1,0]
])

C = np.array([
              [1,2],
              [3,4]
])

D=np.array([
            [1,2,3,4,5]
])

E= np.array([
             [1],
             [2],
             [3]
])

In [ ]:
print('La matriz A es de tamaño, {}'.format(A.shape))
print('La matriz B es de tamaño, {}'.format(B.shape))
print('La matriz C es de tamaño, {}'.format(C.shape))
print('La matriz D es de tamaño, {}'.format(D.shape))
print('La matriz E es de tamaño, {}'.format(E.shape))

La matriz A es de tamaño, (3, 3)
La matriz B es de tamaño, (3, 3)
La matriz C es de tamaño, (2, 2)
La matriz D es de tamaño, (1, 5)
La matriz E es de tamaño, (3, 1)


##Suma y resta de matrices

In [ ]:
if A.shape == B.shape:
  #Suma de matrices
  X=A+B
  print('X={}'.format(X))
  #Resta de matrices
  Y=A-B
  print('Y={}'.format(Y))

  #o bien
  assert A.shape==A.shape
  A+B
  A-B
  

X=[[0 3 4]
 [4 6 6]
 [8 7 9]]
Y=[[2 1 2]
 [4 4 6]
 [6 9 9]]


##Multiplicacion de matrices

###Producto Elemento a Elemento

In [ ]:
assert A.shape == B.shape
X = A * B
print('X=A*B')
print(' ={}'.format(X))

X=A*B
 =[[-1  2  3]
 [ 0  5  0]
 [ 7 -8  0]]


###Prducto matricial

In [ ]:
X= A @ B

In [ ]:
print(X)

[[2 0 1]
 [2 3 4]
 [2 6 7]]


##La transpuesta de una matriz

In [ ]:
print('El tamaño de la matriz D es {}'.format(D.shape))
print('El tamaño de la matriz D transpuesta D^T es {}'.format(D.T.shape))

El tamaño de la matriz D es (1, 5)
El tamaño de la matriz D transpuesta D^T es (5, 1)


In [ ]:
print(E.shape)

(3, 1)


In [ ]:
X=E.T
print(X.shape)

(1, 3)


##La traza de una matriz cuadrada

In [ ]:
np.trace(A)

15

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##La inversa de una matriz

In [ ]:
#Ejemplo: Inversa de la matriz B
X=np.linalg.inv(B)
print(X)

[[-0.  1.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  1.]]


In [ ]:
#Verificamos la inversa de B, multiplicando B B^-1 = I, esperando obtener la matriz identidad
B @ X

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##El determinante de una matriz

In [ ]:
#Ejemplo: Calcule el determinante de la matriz C
x=np.linalg.det(C)
print(x)

-2.0000000000000004


##Resolver un sistema de ecuaciones lineales

In [ ]:
#Considere el siguiente sistema de ecuaciones lineales
"""
ecuacion1=2x + 3y + 1z = 2
ecuacion2=-1x + 2y + 3z = 5
ecuacion3=7x + 5y - 1z = 3
"""
#el cual reescribimos en notacion matricial, Ax = b, de la siguiente manera
A=np.array([
            [2,3,1],
            [-1,2,3],
            [7,5,-1]
])

b=np.array([
            [2],
            [5],
            [3]
])

In [ ]:
#Calculamos los valores de x,y,z que satisfaces a las tres ecuaciones simultaneamente
x=np.linalg.solve(A,b)
print(x)

[[ 3.85714286]
 [-3.71428571]
 [ 5.42857143]]


In [ ]:
#Verficamos la solucion para x, si x es una soluciones entonces
x.shape

(3, 1)

In [ ]:
#el producto matricial entre A y la solucion encontrada x me debe dar b
Y = A @ x 

In [ ]:
#una manera de verificar que el producto matricial Y=Ax es igual a b es calculando la resta 
Y-b

array([[8.8817842e-16],
       [0.0000000e+00],
       [8.8817842e-16]])

In [ ]:
"""
si la resta es igual a cero entonces verfico que es una solucion. Pero esto no es necesario
puesto que el paquete numpy de python ha sido extensivamente probado y se puede considerar
como una implementacion correcta de matematicas en programacion.
"""